Vagrant.configure("2") do |config|

    config.vm.define "child" do |child|
        child.vm.box = "generic/ubuntu2204"
        child.vm.network "private_network", ip: "192.168.10.21"
        child.vm.network "public_network", bridge: "en0: Wi-Fi"
        child.vm.hostname = "child"
        child.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end
        child.vm.provision "shell", inline: <<-SHELL
            sudo apt update
            sudo apt install software-properties-common 
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install ansible -y
            ansible --version
            SHELL
        end
end

  